### PR TITLE
Add PURL support to record generation

### PR DESCRIPTION
**Pull request by chromatic**
See the PURL spec and the CPAN-specific PURL spec:

 * https://github.com/package-url/purl-spec
 * https://github.com/package-url/purl-spec/blob/master/PURL-TYPES.rst#cpan

The algorithm for generation matches that used in URI::PackageURL.

This change is necessary but not necessarily sufficient to use this security database as a source to the Open Source Vulnerabilities aggregator, as described in the [OSV announcement](https://security.googleblog.com/2021/06/announcing-unified-vulnerability-schema.html).

I've marked this as a draft because I'm interested to discuss the goal I've laid out here, and am happy to revise the implementation, if desired.

### CODE REVIEW

**Comment by briandfoy** [comment]
I don't mind adding other fields, and a purl field will be fine. However, after reading the purl stuff it seems it doesn't quite fit.

* The namespace of a particular Perl distribution is not fixed, so there are a lot of questions about what to put there. It can be empty though.
* The version is problematic since each report here is a collection of reports across the entire lifetime of the package. But the version doesn't have to appear.
* If both of those are blank, there is nothing to do since the purl is a composite field. You know it's cpan (mostly) and you know the distribution name. An additional field the combines those two in a string adds no value. Something else can use the existing reports to do other things.
* Since all the necessary information is already in the report, I don't see what's necessary about this change. Anything that wants to generate this information can already do that.
* I don't see how Google would use the reports in this project directly. We'd have to convert them to their OSV format. As such, there's no need to add additional information in the reports. Instead, we'd repackage what we already have into new output formats.
* I'm already including the GitHub ID for these issues, but that's not something I could generate from the existing data.
 
But, I'm also wary of any Google project, especially when we already have ways to get this information for other sources that are already doing this work. In two years when Google gets tired of this, we're back to what we've been using for decades.

I think the path forward is a program that converts the data here into the format that Google needs. That doesn't require a change to the CPANSA.pm module.

**Review by stigtsp — COMMENTED** [review]
Some notes:

- Maybe consider using MetaCPAN::Client instead of parsing the HTML from MetaCPAN

- The author for a dist can change over time, so a version number should also be included in any lookup for author

Here is an example that uses MetaCPAN::Client to get the data needed for a pURL for an old version of CPAN::Audit that had a different author:

```perl
my $mc = MetaCPAN::Client->new();                                                                                         
                                                                                                                           
my ($r) = $mc->release({                                                                                                  
  all => [                                                                                                                
    { distribution => "CPAN-Audit" },                                                                                     
    { version      => "0.15" }                                                                                            
  ]                                                                                                                       
})->next;                                                                                                                 

say "pkg:cpan/" . $r->author . "/" . $r->distribution . "@". $r->version_numified; 
# prints "pkg:cpan/VTI/CPAN-Audit@0.15", and should probably use URI::PackageURL
```

**Review by briandfoy — CHANGES_REQUESTED** [review]
I don't think this is the right place for the change, but if we are going to do it here, I think it needs two major changes:

* leave off the namespace in the purl
* use the MetaCPAN::Client stuff

**Comment by briandfoy** [comment]
Since there was been no response to this, I'm closing this PR simply to keep the queue clean.

**Pull request closed without merging**
